#!/usr/bin/env python3
# coding=utf8

# PREREQUISITES:
# Have unmodified (old) i_cod.sh:
# git checkout ../../../bin/scripts/lib/i_cod.sh
# curl -LO https://registry.npmjs.org/@vscode/codicons/-/codicons-0.0.45.tgz
# tar xzvf codicons-0.0.45.tgz

import json
import os
import re
import sys

# Double-quotes required here, for version-bump.sh:
# version-bump.sh is not working here, need to adjust manually!
version = "3.5.0"

cod_version = '0.0.45'

mappingfile = 'package/src/template/mapping.json' # from codicons-0.0.45.tgz above
glyphsetfile = 'i_cod.sh'
glyphsetsdir = '../../../bin/scripts/lib'

def underscorify(name):
    return name.replace('-', '_')

def get_preferred(names):
    global oldnames
    for n in names:
        if underscorify(n) in oldnames:
            return underscorify(n)
    return underscorify(names[0])

def createGlyphInfo(icon_datasets, filepathname, into):
    """ Write the glyphinfo file """
    with open(filepathname, 'w', encoding = 'utf8') as f:
        f.write(u'#!/usr/bin/env bash\n')
        f.write(intro)
        f.write(u'# Script Version: (autogenerated)\n')
        f.write(u'test -n "$__i_cod_loaded" && return || __i_cod_loaded=1\n')
        for (codepoint, names) in icon_datasets:
            #codepoint = int(codepoint, 16)
            name = get_preferred(names)
            f.write(u"i='{}' i_cod_{}=$i\n".format(chr(codepoint), name))
            #for more_names in name[1:]:
             #   f.write(u"      i_cod_{}=$i\n".format(more_names))
        f.write(u'unset i\n')

print('Reading old GlyphInfo {}'.format(glyphsetfile))
oldnames = []
with open(os.path.join(glyphsetsdir, glyphsetfile), 'r') as f:
    pat = r' i_cod_([^ =]*)'
    for line in f:
        if len(line) < 1 or line[0] != 'i':
            continue
        m = re.search(pat, line)
        if m:
            oldnames.append(m.group(1))
print('Found {} entries'.format(len(oldnames)))

print('Reading mapping file')
with open(mappingfile, 'r') as f:
    mapping = json.load(f)
print('Found {} entries'.format(len(mapping)))

if ('repo-fetch' in mapping['60445']
    and 'git-fetch' not in mapping['60445']):
    mapping['60445'].append('git-fetch')
    print('Adding forgotten "git-fetch" to newer "repo-fetch"')

codepoints = [ int(c) for c in mapping.keys() ]
codepoints.sort()
num_icons = len(codepoints)
min_code = min(codepoints)
max_code = max(codepoints)
has_gaps = max_code - min_code + 1 != num_icons

intro  = u'# Codicons (version {}, {} icons)\n'.format(cod_version, num_icons)
intro += u'# Codepoints: {:X}-{:X}{}\n'.format(min_code, max_code, ' with gaps' if has_gaps else '')
intro += u'# Nerd Fonts Version: {}\n'.format(version)

print('Generating GlyphInfo {}'.format(glyphsetfile))
print(intro)
createGlyphInfo(
    [ tuple([c, mapping[str(c)]]) for c in codepoints ],
    os.path.join(glyphsetsdir, glyphsetfile),
    intro)
print('Finished')
